// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAln0T1k3D3j_J4yYi81HVOBa25fZQRlfY',
    appId: '1:523377696722:web:cd912ca7e72ef2e1a3f20b',
    messagingSenderId: '523377696722',
    projectId: 'quizeverse-43f19',
    authDomain: 'quizeverse-43f19.firebaseapp.com',
    storageBucket: 'quizeverse-43f19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpu_UsfFqvjuAWgvi5QN2Ka1pYqggHTjs',
    appId: '1:523377696722:android:04937b0ab6bcea48a3f20b',
    messagingSenderId: '523377696722',
    projectId: 'quizeverse-43f19',
    storageBucket: 'quizeverse-43f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGARjWy6WRVw0TRB_fbBC8DkwXlc7XlEU',
    appId: '1:523377696722:ios:5259dfc8be08a974a3f20b',
    messagingSenderId: '523377696722',
    projectId: 'quizeverse-43f19',
    storageBucket: 'quizeverse-43f19.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGARjWy6WRVw0TRB_fbBC8DkwXlc7XlEU',
    appId: '1:523377696722:ios:5259dfc8be08a974a3f20b',
    messagingSenderId: '523377696722',
    projectId: 'quizeverse-43f19',
    storageBucket: 'quizeverse-43f19.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAln0T1k3D3j_J4yYi81HVOBa25fZQRlfY',
    appId: '1:523377696722:web:0c411a33f80c7b1ea3f20b',
    messagingSenderId: '523377696722',
    projectId: 'quizeverse-43f19',
    authDomain: 'quizeverse-43f19.firebaseapp.com',
    storageBucket: 'quizeverse-43f19.firebasestorage.app',
  );
}
